DROP TABLE IF EXISTS CARE_ALLERGIES;
CREATE TABLE CARE_ALLERGIES
(
    AllergiesID INTEGER NOT NULL,
    InterventionID INTEGER,
    PersonID INTEGER,
    AllergyCode STRING,
    AllergyDesc STRING,
    ClinicalDateTime STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER,
    ApplicationID STRING,
    FacilitiesID STRING);
ALTER TABLE CARE_ALLERGIES ADD CONSTRAINT xpk_CARE_ALLERGIES PRIMARY KEY(AllergiesID);

DROP TABLE IF EXISTS CARE_DIAGNOSIS;
CREATE TABLE CARE_DIAGNOSIS(
    DiagnosisID INTEGER NOT NULL,
    Diagnosis STRING,
    DiagnosisModifier STRING,
    DiagnosisDateTime STRING,
    InterventionID INTEGER,
    PersonID INTEGER,
    CreatedDate TIMESTAMP,
    StatusID INTEGER,
    ApplicationID STRING,
    FacilityID STRING
);
ALTER TABLE CARE_DIAGNOSIS ADD CONSTRAINT xpk_CARE_DIAGNOSIS PRIMARY KEY(DiagnosisID);

DROP TABLE IF EXISTS CARE_GENOMICS;
CREATE TABLE CARE_GENOMICS(
    GenomicsID INTEGER NOT NULL,
    InterventionID INTEGER,
    PersonID INTEGER,
    GenomicsLink STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER,
    ApplicationID STRING,
    FacilitiesID STRING
    );
ALTER TABLE CARE_GENOMICS ADD CONSTRAINT xpk_CARE_GENOMICS PRIMARY KEY(GenomicsID);

DROP TABLE IF EXISTS CARE_IMMUNIZATIONS;
CREATE TABLE CARE_IMMUNIZATIONS(
    ImmunizationID INTEGER NOT NULL,
    PersonID INTEGER,
    ImmunizationCode STRING,
    ImmunizationDesc STRING,
    ImmunizationDateTime STRING,
    ImmunizationType STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER,
    ApplicationID STRING,
    FacilitiesID STRING);
ALTER TABLE CARE_IMMUNIZATIONS ADD CONSTRAINT xpk_CARE_IMMUNIZATIONS PRIMARY KEY(ImmunizationID);

DROP TABLE IF EXISTS CARE_INTERVENTIONS;
CREATE TABLE CARE_INTERVENTIONS(
    InterventionID INTEGER NOT NULL,
    AdmitDateTime STRING,
    DischargeDateTime STRING,
    PersonID INTEGER,
    FacilitiesID STRING,
    ApplicationID STRING,
    DateCreated TIMESTAMP,
    StatusID INTEGER);
ALTER TABLE CARE_INTERVENTIONS ADD CONSTRAINT xpk_CARE_INTERVENTIONS PRIMARY KEY(InterventionID);

DROP TABLE IF EXISTS CARE_MEDICATIONS;
CREATE TABLE CARE_MEDICATIONS(
    MedicationID INTEGER NOT NULL,
    InterventionsID INTEGER,
    PersonID INTEGER,
    IncidentDateTime STRING,
    DrugCode STRING,
    DrugName STRING,
    DrugQuantity STRING,
    ScriptDateTime STRING,
    NPI STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER,
    FacilitiesID STRING,
    OrganizationID STRING);
ALTER TABLE CARE_MEDICATIONS ADD CONSTRAINT xpk_CARE_MEDICATIONS PRIMARY KEY(MedicationID);

DROP TABLE IF EXISTS CARE_OBSERVATIONS;
CREATE TABLE CARE_OBSERVATIONS(
      ObservationsID INTEGER NOT NULL,
      InterventionsID INTEGER,
      PersonID INTEGER,
      OrderNumberID STRING,
      ObservationCode STRING,
      ObservationUnit STRING,
      ReferenceRange STRING,
      AbnormalFlags STRING,
      Probability STRING,
      AbnormalTestNature STRING,
      ProducerID STRING,
      ObservationMethod STRING,
      ValueType STRING,
      ObservationDateTime STRING,
      StatusID INTEGER,
      CreatedDate TIMESTAMP,
      OrganizationID STRING,
      FacilitiesID STRING);
ALTER TABLE CARE_OBSERVATIONS ADD CONSTRAINT xpk_CARE_OBSERVATIONS PRIMARY KEY(ObservationsID);

DROP TABLE IF EXISTS CARE_ORDERS;
CREATE TABLE CARE_ORDERS(
    OrderNumberID INTEGER NOT NULL,
    InterventionsID INTEGER,
    PersonID INTEGER,
    FillerOrderNumber STRING,
    FiillerGroupNumber STRING,
    OrderControlType STRING,
    OrderingPhysicianID STRING,
    OrderEffectiveDate STRING,
    OrderControlReason STRING,
    OrderStatusModifier STRING,
    Confidentiality STRING,
    OrderType STRING,
    OrderingDevice STRING,
    OrderDate STRING,
    OrderTime STRING,
    OrderStatus STRING,
    StatusID INTEGER,
    CreatedDate TIMESTAMP,
    FacilitiesID STRING,
    OrganizationID STRING);
ALTER TABLE CARE_ORDERS ADD CONSTRAINT xpk_CARE_ORDERS PRIMARY KEY(OrderNumberID);

DROP TABLE IF EXISTS CARE_PROBLEMS;
CREATE TABLE CARE_PROBLEMS(
    ProblemID INTEGER NOT NULL,
    InterventionID INTEGER,
    PersonID INTEGER,
    ProblemCode STRING,
    ProblemDesc STRING,
    ClinicalDateTime STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER,
    OrganizationID STRING,
    FacilitiesID STRING);
ALTER TABLE CARE_PROBLEMS ADD CONSTRAINT xpk_CARE_PROBLEMS PRIMARY KEY(ProblemID);

DROP TABLE IF EXISTS CARE_PROCEDURES;
CREATE TABLE CARE_PROCEDURES(
    ProceduresID INTEGER NOT NULL,
    InterventionID INTEGER,
    PersonID INTEGER,
    ProcedureCode STRING,
    ProcedureModifierCode STRING,
    ProcedureDesc STRING,
    ProcedureCodeDateTime STRING,
    ProcedureCodeType STRING,
    DateCreated TIMESTAMP,
    StatusID INTEGER,
    ApplicationID STRING,
    OrganizationID STRING);
ALTER TABLE CARE_PROCEDURES ADD CONSTRAINT xpk_CARE_PROCEDURES PRIMARY KEY(ProceduresID);

DROP TABLE IF EXISTS CARE_PROVIDERS;
CREATE TABLE CARE_PROVIDERS(
    ProviderID INTEGER NOT NULL,
    InterventionsID INTEGER,
    PersonID INTEGER,
    PhysicianExternalID STRING,
    NameFirst STRING,
    NameMiddle STRING,
    NameLast STRING,
    NPI STRING,
    Address STRING,
    Address2 STRING,
    City STRING,
    StateID STRING,
    PostalCode STRING,
    PhoneNumber STRING,
    FaxNumber STRING,
    MobileNumber STRING,
    OrganizationID STRING,
    PlatformAppID STRING,
    Specialty STRING,
    DateCreated TIMESTAMP,
    StatusID INTEGER);
ALTER TABLE CARE_PROVIDERS ADD CONSTRAINT xpk_CARE_PROVIDERS PRIMARY KEY(ProviderID);

DROP TABLE IF EXISTS CARE_REPORTS;
CREATE TABLE CARE_REPORTS(
    ReportsID INTEGER NOT NULL,
    InterventionID INTEGER,
    PersonID INTEGER,
    ReportLink STRING,
    ReportDateTime STRING,
    DateCreated TIMESTAMP,
    StatusID INTEGER);
ALTER TABLE CARE_REPORTS ADD CONSTRAINT xpk_CARE_REPORTS PRIMARY KEY(ReportsID);

DROP TABLE IF EXISTS CARE_VITALS;
CREATE TABLE CARE_VITALS(
    VitalsID INTEGER NOT NULL,
    InterventionID INTEGER,
    PersonID INTEGER,
    DateTimeReported STRING,
    VitalType STRING,
    Vital STRING,
    VitalNotes STRING,
    StatusID INTEGER,
    CreatedDate TIMESTAMP,
    ApplicationID STRING,
    OrganizationID STRING);
ALTER TABLE CARE_VITALS ADD CONSTRAINT xpk_CARE_VITALS PRIMARY KEY(VitalsID);

DROP TABLE IF EXISTS CARE_PERSON;
CREATE TABLE CARE_PERSON(
    PersonID INTEGER NOT NULL,
    NameFirst STRING,
    NameMiddle STRING,
    NameLast STRING,
    NameSuffix STRING,
    DLN STRING,
    DLNState STRING,
    SSN STRING,
    DOB STRING,
    OrganizationID STRING,
    ApplicationID STRING,
    UID STRING,
    CreatedDate TIMESTAMP,
    Status INTEGER);
ALTER TABLE CARE_PERSON ADD CONSTRAINT xpk_CARE_PERSON PRIMARY KEY(PersonID);

DROP TABLE IF EXISTS PERSON_ACCOUNTS;
    CREATE TABLE PERSON_ACCOUNTS(
    PersonAccountsID INTEGER NOT NULL,
    PersonID INTEGER,
    PatientID STRING,
    AltPatientID STRING,
    AccountNumber STRING,
    CustomAccountNumber STRING,
    EMPI STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER,
    OrganizationID STRING,
    ApplicationID STRING);
ALTER TABLE PERSON_ACCOUNTS ADD CONSTRAINT xpk_PERSON_ACCOUNTS PRIMARY KEY(PersonAccountsID);

DROP TABLE IF EXISTS PERSON_ADDRESSES;
CREATE TABLE PERSON_ADDRESSES(
    PersonAddressID INTEGER NOT NULL,
    PersonID INTEGER,
    Address STRING,
    Address2 STRING,
    City STRING,
    StateID STRING,
    PostalCode STRING,
    CountryID STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER,
    ApplicationID STRING,
    OrganizationID STRING);
ALTER TABLE PERSON_ADDRESSES ADD CONSTRAINT xpk_PERSON_ADDRESSES PRIMARY KEY(PersonAddressID);

DROP TABLE IF EXISTS PERSON_DEMOGRAPHICS;
CREATE TABLE PERSON_DEMOGRAPHICS(
    PersonDemographicID INTEGER NOT NULL,
    PersonID INTEGER,
    DemographicInfoTypeID STRING,
    CodeValue STRING,
    CodeDesc STRING,
    Address STRING,
    City STRING,
    StateID STRING,
    PhoneNumber STRING,
    CustomData STRING,
    CreatedDate date NOT NULL,
    StatusID INTEGER,
    ApplicationID STRING,
    OrganizationID STRING);
ALTER TABLE PERSON_DEMOGRAPHICS ADD CONSTRAINT xpk_PERSON_DEMOGRAPHICS PRIMARY KEY(PersonDemographicID);

DROP TABLE IF EXISTS PERSON_EMPLOYERS;
CREATE TABLE PERSON_EMPLOYERS(
    PersonEmployerID INTEGER NOT NULL,
    PersonID INTEGER,
    EmployerCode STRING,
    EmployerName STRING,
    EmployerAddress STRING,
    EmployerCityStateZip STRING,
    JobTitle STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER,
    ApplicationID STRING,
    OrganizationID STRING);
ALTER TABLE PERSON_EMPLOYERS ADD CONSTRAINT xpk_PERSON_EMPLOYERS PRIMARY KEY(PersonEmployerID);

DROP TABLE IF EXISTS PERSON_EXTRNLCOMMUNICATIONS;
CREATE TABLE PERSON_EXTRNLCOMMUNICATIONS(
    CommunictionID INTEGER NOT NULL,
    PersonID INTEGER,
    CommunicationDateTime TIMESTAMP,
    CommunicationType STRING,
    CommunicationDetails STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER,
    ApplicationID STRING,
    OrganizationID STRING);
ALTER TABLE PERSON_EXTRNLCOMMUNICATIONS ADD CONSTRAINT xpk_PERSON_EXTRNLCOMMUNICATIONS PRIMARY KEY(CommunictionID);

DROP TABLE IF EXISTS PERSON_EXTRNLDEVICEASSOCIATION;
CREATE TABLE PERSON_EXTRNLDEVICEASSOCIATION(
    DeviceAssociationID INTEGER NOT NULL,
    PersonID INTEGER,
    DeviceAssociationDateTime TIMESTAMP,
    DeviceID STRING,
    DeviceDetails STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER,
    ApplicationID STRING,
    OrganizationID STRING);
ALTER TABLE PERSON_EXTRNLDEVICEASSOCIATION ADD CONSTRAINT xpk_PERSON_EXTRNLDEVICEASSOCIATION PRIMARY KEY(DeviceAssociationID);

DROP TABLE IF EXISTS REFDATA_APPLICATION;
CREATE TABLE REFDATA_APPLICATION(
    ApplicationID STRING NOT NULL,
    ApplicationName STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER);
ALTER TABLE REFDATA_APPLICATION ADD CONSTRAINT xpk_REFDATA_APPLICATION PRIMARY KEY(ApplicationID);

DROP TABLE IF EXISTS REFDATA_FACILITIES;
CREATE TABLE REFDATA_FACILITIES(
    FacilitiesID STRING NOT NULL,
    FacilitiesName STRING,
    Address STRING,
    Address2 STRING,
    City STRING,
    State STRING,
    CountryID STRING,
    PostalCode STRING,
    Notes STRING,
    LicenseNumber STRING,
    LicenseType STRING,
    LicensedState STRING,
    OID STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER);
ALTER TABLE REFDATA_FACILITIES ADD CONSTRAINT xpk_REFDATA_FACILITIES PRIMARY KEY(FacilitiesID);

DROP TABLE IF EXISTS REFDATA_OIDS;
CREATE TABLE REFDATA_OIDS(
    OIDID STRING NOT NULL,
    OIDDesc STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER);
ALTER TABLE REFDATA_OIDS ADD CONSTRAINT xpk_REFDATA_OIDS PRIMARY KEY(OIDID);

DROP TABLE IF EXISTS REFDATA_ORGANIZATION;
CREATE TABLE REFDATA_ORGANIZATION(
    OrganizationID STRING NOT NULL,
    OrganizationName STRING,
    Address STRING,
    Address2 STRING,
    City STRING,
    State STRING,
    Country STRING,
    PostalCode STRING,
    Notes STRING,
    LicenseNumber STRING,
    LicenseType STRING,
    LicensedState STRING,
    IncorporatedState STRING,
    OIDID STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER);
ALTER TABLE REFDATA_ORGANIZATION ADD CONSTRAINT xpk_REFDATA_ORGANIZATION PRIMARY KEY(OrganizationID);

DROP TABLE IF EXISTS REFDATA_STATUS;
CREATE TABLE REFDATA_STATUS(
    StatusID INTEGRER NOT NULL,
    StatusDescription STRING,
    CreatedDate TIMESTAMP);
ALTER TABLE REFDATA_STATUS ADD CONSTRAINT xpk_REFDATA_STATUS PRIMARY KEY(StatusID);

DROP TABLE IF EXISTS REFDATA_USSTATES;
CREATE TABLE REFDATA_USSTATES(
    StateID STRING NOT NULL,
    StateDescription STRING NOT NULL,
    CreatedDate TIMESTAMP,
    StatusID INTEGER);
ALTER TABLE REFDATA_USSTATES ADD CONSTRAINT xpk_REFDATA_USSTATES PRIMARY KEY(StateID);

DROP TABLE IF EXISTS TERMS_TERMDATA;
CREATE TABLE TERMS_TERMDATA(
    TermID INTEGER NOT NULL,
    CodeIdentifier STRING,
    TermText STRING,
    TermGroup STRING,
    AlternativeID STRING,
    AlternativeText STRING,
    AlternativeTermGroup STRING,
    FacilitiesID STRING,
    OrganizationID STRING,
    CreatedDate TIMESTAMP,
    StatusID INTEGER);
ALTER TABLE TERMS_TERMDATA ADD CONSTRAINT xpk_TERMS_TERMDATA PRIMARY KEY(TermID);